
  trigger:
  branches:
    include:
      - main

variables:
  - group: terraform_credential
  terraformDirectory: '$(Build.SourcesDirectory)/app'
  pythonVersion: '3.10'
  devWebAppName: 'webapp-faruk-dev-001'
  stagingWebAppName: 'webapp-faruk-staging-001'
  devResourceGroup: 'webapp-rg-dev'
  stagingResourceGroup: 'webapp-rg-staging'

stages:
  # Stage 1: Build Application
  - stage: Build
    displayName: 'Build Application'
    jobs:
      - job: build
        displayName: 'Build Package'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
              addToPath: true

          - script: |
              pip install -r $(Build.SourcesDirectory)/src/requirements.txt
              echo "gunicorn --bind=0.0.0.0:5000 --timeout 600 app:app" > $(Build.SourcesDirectory)/src/startup.sh
              chmod +x $(Build.SourcesDirectory)/src/startup.sh
            displayName: 'Prepare Application'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/src'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
              replaceExistingArchive: true

          - publish: '$(Build.ArtifactStagingDirectory)/app.zip'
            artifact: 'webapp-package'

  # Stage 2: Dev Environment
  - stage: Dev
    displayName: 'Dev Deployment'
    dependsOn: Build
    jobs:
      - job: terraform_dev
        displayName: 'Provision Dev'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.5.5'

          - script: |
              terraform init -input=false
              terraform workspace new dev || true
              terraform workspace select dev
              terraform plan -out=tfplan -var="resource_group_name=$(devResourceGroup)" -var="app_service_name=$(devWebAppName)"
              terraform apply -auto-approve tfplan
            displayName: 'Terraform Dev'
            workingDirectory: $(terraformDirectory)

      - job: deploy_dev
        displayName: 'Deploy to Dev'
        dependsOn: terraform_dev
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - download: current
            artifact: 'webapp-package'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'terraform-sc'
              appType: 'webAppLinux'
              appName: '$(devWebAppName)'
              package: '$(Pipeline.Workspace)/webapp-package/app.zip'
              runtimeStack: 'PYTHON|$(pythonVersion)'
              startupCommand: 'bash startup.sh'

  # Stage 3: Staging Environment
  - stage: Staging
    displayName: 'Staging Deployment'
    dependsOn: Dev
    condition: succeeded()
    jobs:
      - job: terraform_staging
        displayName: 'Provision Staging'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.5.5'

          - script: |
              terraform init -input=false
              terraform workspace new staging || true
              terraform workspace select staging
              terraform plan -out=tfplan -var="resource_group_name=$(stagingResourceGroup)" -var="app_service_name=$(stagingWebAppName)"
              terraform apply -auto-approve tfplan
            displayName: 'Terraform Staging'
            workingDirectory: $(terraformDirectory)

      - job: deploy_staging
        displayName: 'Deploy to Staging'
        dependsOn: terraform_staging
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - download: current
            artifact: 'webapp-package'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'terraform-sc'
              appType: 'webAppLinux'
              appName: '$(stagingWebAppName)'
              package: '$(Pipeline.Workspace)/webapp-package/app.zip'
              runtimeStack: 'PYTHON|$(pythonVersion)'
              startupCommand: 'bash startup.sh'
