trigger:
  branches:
    include:
      - main

variables:
  - group: terraform_credential
  - name: pythonVersion
    value: '3.10'
  - name: tfWorkingDir
    value: 'infra'
  - name: terraformVersion
    value: '1.5.7'
  - name: location
    value: 'East US'

  # Environment configurations
  - name: dev.app_service_name
    value: 'my-dev-webapp'
  - name: staging.app_service_name
    value: 'my-staging-webapp'

  # Common
  - name: app_service_plan_name
    value: 'my-app-service-plan'

pool:
  vmImage: 'ubuntu-24.04'

stages:
  - stage: TerraformInitPlanApply
    displayName: 'Terraform Init, Plan, Apply'
    jobs:
      - job: TerraformJob
        displayName: 'Terraform Initialization and Apply'
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '$(terraformVersion)'

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'terraform-sc'
              workingDirectory: '$(tfWorkingDir)'
              backendAzureRmResourceGroupName: 'terraform-backend-rg'
              backendAzureRmStorageAccountName: 'tfstatefaruk1234567'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraform.tfstate'

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(tfWorkingDir)'
              backendServiceArm: 'terraform-sc'
              environmentServiceNameAzureRM: 'terraform-sc'
              vars: |
                location = '$(location)'

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(tfWorkingDir)'
              backendServiceArm: 'terraform-sc'
              environmentServiceNameAzureRM: 'terraform-sc'
              vars: |
                location = '$(location)'
              commandOptions: '-auto-approve'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'terraform-sc'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Dev Web App URL: $(dev_web_app_url)"
                echo "Staging Web App URL: $(staging_web_app_url)"

