trigger:
  paths:
    include:
      - app/*
      - pipeline/azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: terraform_credential  # Contains: ARM_SUBSCRIPTION_ID, ARM_CLIENT_ID, ARM_CLIENT_SECRET, ARM_TENANT_ID
  - name: pythonVersion
    value: '3.10'
  - name: tfWorkingDir
    value: 'app/infra'

stages:
  # ------------------- Build Stage -------------------
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
              addToPath: true

          - script: |
              cd app
              python -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
            displayName: 'Install Dependencies'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'app'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)/app.zip
            artifact: drop

  # ------------------- Dev Stage -------------------
  - stage: Dev
    displayName: 'Dev Deployment'
    dependsOn: Build
    jobs:
      - job: DevInfraAndDeploy
        steps:
          - checkout: self
          - download: current
            artifact: drop

          - task: AzureCLI@2
            displayName: 'Install Terraform'
            inputs:
              azureSubscription: 'terraform-sc'
              scriptType: 'bash'
              inlineScript: |
                sudo apt-get update
                sudo apt-get install -y wget unzip
                wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
                sudo unzip terraform_1.5.7_linux_amd64.zip -d /usr/local/bin/
                terraform version

          - script: |
              cd $(tfWorkingDir)
              terraform init
              terraform validate
              terraform apply -auto-approve
            displayName: 'Deploy Infrastructure'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'terraform-sc'
              appType: 'webAppLinux'
              appName: '$(app_service_name)'  # From variable group
              package: '$(Pipeline.Workspace)/drop/app.zip'

  # ------------------- Staging Stage -------------------
  - stage: Staging
    displayName: 'Staging Deployment'
    dependsOn: Dev
    jobs:
      - job: DeployStaging
        steps:
          - checkout: self
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'terraform-sc'
              appType: 'webAppLinux'
              appName: 'webapp-faruk-staging-001'
              package: '$(Pipeline.Workspace)/drop/app.zip'
