trigger:
  paths:
    include:
      - app/*
      - infra/*
      - pipeline/azure-pipelines.yml

variables:
  - group: terraform_credential
  - name: pythonVersion
    value: '3.10'
  - name: tfWorkingDir
    value: 'infra'
  - name: terraformVersion
    value: '1.5.7'

  # Dev
  - name: environment_dev
    value: 'dev'
  - name: app_service_name_dev
    value: 'demo-app-faruk-dev-001'
  - name: resource_group_name_dev
    value: 'my-resource-group-dev'

  # Staging
  - name: environment_staging
    value: 'staging'
  - name: app_service_name_staging
    value: 'webapp-faruk-staging-001'
  - name: resource_group_name_staging
    value: 'my-resource-group-staging'

  # Common
  - name: app_service_plan_name
    value: 'my-app-service-plan'

pool:
  vmImage: 'ubuntu-24.04'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build and Package App'
        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'

          - script: |
              cd app
              python -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
            displayName: 'Install Dependencies'

          - task: ArchiveFiles@2
            displayName: 'Archive Application'
            inputs:
              rootFolderOrFile: 'app'
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
              replaceExistingArchive: true

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/app.zip'
              artifact: 'drop'

  - stage: Dev
    displayName: 'Deploy to Dev'
    dependsOn: Build
    jobs:
      - job: DeployDev
        displayName: 'Terraform & App Deployment (Dev)'
        steps:
          - checkout: self
          - download: current
            artifact: drop

          - script: |
              sudo apt-get update
              sudo apt-get install -y wget unzip
              wget https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip
              unzip terraform_$(terraformVersion)_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
              terraform -version
            displayName: 'Install Terraform'

          - script: |
              terraform init -input=false -reconfigure \
                -backend-config="resource_group_name=terraform-backend-rg" \
                -backend-config="storage_account_name=tfstatefaruk1234567" \
                -backend-config="container_name=tfstate" \
                -backend-config="key=$(environment_dev).terraform.tfstate"
            workingDirectory: '$(tfWorkingDir)'
            displayName: 'Terraform Init (Dev)'
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

          - script: |
              export TF_VAR_resource_group_name=$(resource_group_name_dev)
              export TF_VAR_environment=$(environment_dev)
              export TF_VAR_app_service_name=$(app_service_name_dev)
              export TF_VAR_app_service_plan_name=$(app_service_plan_name)

              terraform plan -out=tfplan
            workingDirectory: '$(tfWorkingDir)'
            displayName: 'Terraform Plan (Dev)'
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

          - script: |
              terraform apply -auto-approve tfplan
            workingDirectory: '$(tfWorkingDir)'
            displayName: 'Terraform Apply (Dev)'
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

          - task: AzureWebApp@1
            displayName: 'Deploy to Web App (Dev)'
            inputs:
              azureSubscription: 'terraform-sc'
              appType: 'webAppLinux'
              appName: '$(app_service_name_dev)'
              package: '$(Pipeline.Workspace)/drop/app.zip'
              runtimeStack: 'PYTHON|3.10'
              startUpCommand: 'gunicorn --bind=0.0.0.0 --workers=4 app:app:app'

  - stage: Staging
    displayName: 'Deploy to Staging'
    dependsOn: Dev
    condition: succeeded()
    jobs:
      - job: DeployStaging
        displayName: 'Terraform & App Deployment (Staging)'
        steps:
          - checkout: self
          - download: current
            artifact: drop

          - script: |
              sudo apt-get update
              sudo apt-get install -y wget unzip
              wget https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip
              unzip terraform_$(terraformVersion)_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
              terraform -version
            displayName: 'Install Terraform'

          - script: |
              terraform init -input=false -reconfigure \
                -backend-config="resource_group_name=terraform-backend-rg" \
                -backend-config="storage_account_name=tfstatefaruk1234567" \
                -backend-config="container_name=tfstate" \
                -backend-config="key=$(environment_staging).terraform.tfstate"
            workingDirectory: '$(tfWorkingDir)'
            displayName: 'Terraform Init (Staging)'
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

          - script: |
              export TF_VAR_resource_group_name=$(resource_group_name_staging)
              export TF_VAR_environment=$(environment_staging)
              export TF_VAR_app_service_name=$(app_service_name_staging)
              export TF_VAR_app_service_plan_name=$(app_service_plan_name)

              terraform plan -out=tfplan
            workingDirectory: '$(tfWorkingDir)'
            displayName: 'Terraform Plan (Staging)'
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

          - script: |
              terraform apply -auto-approve tfplan
            workingDirectory: '$(tfWorkingDir)'
            displayName: 'Terraform Apply (Staging)'
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

          - task: AzureWebApp@1
            displayName: 'Deploy to Web App (Staging)'
            inputs:
              azureSubscription: 'terraform-sc'
              appType: 'webAppLinux'
              appName: '$(app_service_name_staging)'
              package: '$(Pipeline.Workspace)/drop/app.zip'
              runtimeStack: 'PYTHON|3.10'
              startUpCommand: 'gunicorn --bind=0.0.0.0 --workers=4 app:app:app'

