trigger:
  paths:
    include:
      - app/*
      - pipeline/azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: terraform_credential
  - name: pythonVersion
    value: '3.10'

stages:
  # ------------------- Build Stage -------------------
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Install & Package App'
        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
              addToPath: true

          - script: |
              cd app
              python -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
            displayName: 'Install Dependencies'

          - task: ArchiveFiles@2
            displayName: 'Archive App Code'
            inputs:
              rootFolderOrFile: 'app'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)/app.zip
            artifact: drop

  # ------------------- Dev Stage -------------------
  - stage: Dev
    displayName: 'Dev Deployment'
    dependsOn: Build
    jobs:
      - job: DevInfraAndDeploy
        displayName: 'Terraform Apply + App Deploy (Dev)'
        steps:
          - checkout: self

          - download: current
            artifact: drop

          - task: AzureCLI@2
            displayName: 'Install Terraform'
            inputs:
              azureSubscription: 'terraform-sc'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                curl -sL https://apt.releases.hashicorp.com/gpg | gpg --dearmor > hashicorp-archive-keyring.gpg
                sudo install -o root -g root -m 644 hashicorp-archive-keyring.gpg /usr/share/keyrings/
                echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
                sudo apt update && sudo apt install terraform -y
                terraform -version

          - script: |
              cd app
              terraform init
              terraform apply -auto-approve
            displayName: 'Terraform Deploy Dev'

          - task: AzureWebApp@1
            displayName: 'Deploy App to Dev'
            inputs:
              azureSubscription: 'terraform-sc'
              appType: 'webAppLinux'
              appName: 'webapp-faruk-dev-001'
              package: '$(Pipeline.Workspace)/drop/app.zip'

  # ------------------- Staging Stage -------------------
  - stage: Staging
    displayName: 'Staging Deployment'
    dependsOn: Dev
    jobs:
      - job: DeployStaging
        displayName: 'Deploy App to Staging'
        steps:
          - checkout: self

          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: 'Deploy App to Staging'
            inputs:
              azureSubscription: 'terraform-sc'
              appType: 'webAppLinux'
              appName: 'webapp-faruk-staging-001'
              package: '$(Pipeline.Workspace)/drop/app.zip'

