trigger:
  paths:
    include:
      - app/*
      - infra/*
      - pipeline/azure-pipelines.yml

variables:
  - group: terraform_credential
  - name: pythonVersion
    value: '3.10'
  - name: tfWorkingDir
    value: 'infra'
  - name: terraformVersion
    value: '1.5.7'
  - name: environment_dev
    value: 'dev'
  - name: environment_staging
    value: 'staging'
  - name: app_service_name_dev
    value: 'demo-app-faruk-dev-001'
  - name: app_service_name_staging
    value: 'webapp-faruk-staging-001'
  - name: resource_group_name_dev
    value: 'my-resource-group-dev'
  - name: resource_group_name_staging
    value: 'my-resource-group-staging'

pool:
  vmImage: 'ubuntu-24.04'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
              addToPath: true
              architecture: 'x64'

          - script: |
              cd app
              python -m venv venv
              source venv/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install Python Dependencies'

          - task: ArchiveFiles@2
            displayName: 'Package Application'
            inputs:
              rootFolderOrFile: 'app'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
              replaceExistingArchive: true
              excludeFiles: |
                **/infra/**
                **/__pycache__/**

          - publish: $(Build.ArtifactStagingDirectory)/app.zip
            artifact: drop

  - stage: Dev
    displayName: 'Dev Environment Deployment'
    dependsOn: Build
    jobs:
      - job: DeployDev
        steps:
          - checkout: self
          - download: current
            artifact: drop

          - task: Bash@3
            displayName: 'Install Terraform'
            inputs:
              targetType: 'inline'
              script: |
                sudo apt-get update
                sudo apt-get install -y wget unzip
                wget https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip
                unzip terraform_$(terraformVersion)_linux_amd64.zip
                sudo mv terraform /usr/local/bin/
                terraform -version

          # Step to create backend resources in Azure
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'terraform-sc'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Create Resource Group for Backend
                az group create --name terraform-backend-rg --location eastus

                # Create Storage Account
                az storage account create --name tfstatefaruk1234567 --resource-group terraform-backend-rg --location eastus --sku Standard_LRS

                # Create Container for storing state files
                az storage container create --name tfstate --account-name tfstatefaruk1234567

          - task: Bash@3
            displayName: 'Import Resource Group (Dev)'
            inputs:
              workingDirectory: '$(tfWorkingDir)'
              targetType: 'inline'
              script: |
                terraform init -input=false \
                  -backend-config="resource_group_name=terraform-backend-rg" \
                  -backend-config="storage_account_name=tfstatefaruk1234567" \
                  -backend-config="container_name=tfstate" \
                  -backend-config="key=dev.terraform.tfstate"
                
                # Check if resource group is in Terraform state
                if ! terraform state list | grep -q azurerm_resource_group.rg; then
                  echo "Resource group not found in state. Importing..."
                  terraform import azurerm_resource_group.rg /subscriptions/$(SUBSCRIPTION_ID)/resourceGroups/$(resource_group_name_dev)
                else
                  echo "Resource group already managed by Terraform."
                fi

          - task: Bash@3
            displayName: 'Initialize and Apply Terraform (Dev)'
            inputs:
              workingDirectory: '$(tfWorkingDir)'
              targetType: 'inline'
              script: |
                export TF_LOG=DEBUG
                terraform apply -auto-approve -no-color \
                  -var="app_service_name=$(app_service_name_dev)" \
                  -var="resource_group_name=$(resource_group_name_dev)" \
                  -var="environment=$(environment_dev)"
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App (Dev)'
            inputs:
              azureSubscription: 'terraform-sc'
              appType: 'webAppLinux'
              appName: '$(app_service_name_dev)'
              package: '$(Pipeline.Workspace)/drop/app.zip'
              runtimeStack: 'PYTHON|3.10'
              startUpCommand: 'gunicorn --bind=0.0.0.0 --workers=4 app:app'

  - stage: Staging
    displayName: 'Staging Environment Deployment'
    dependsOn: Dev
    condition: succeeded()
    jobs:
      - job: DeployStaging
        steps:
          - checkout: self
          - download: current
            artifact: drop

          - task: Bash@3
            displayName: 'Install Terraform'
            inputs:
              targetType: 'inline'
              script: |
                sudo apt-get update
                sudo apt-get install -y wget unzip
                wget https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip
                unzip terraform_$(terraformVersion)_linux_amd64.zip
                sudo mv terraform /usr/local/bin/
                terraform -version

          - task: Bash@3
            displayName: 'Import Resource Group (Staging)'
            inputs:
              workingDirectory: '$(tfWorkingDir)'
              targetType: 'inline'
              script: |
                terraform init -input=false \
                  -backend-config="resource_group_name=terraform-backend-rg" \
                  -backend-config="storage_account_name=tfstatefaruk1234567" \
                  -backend-config="container_name=tfstate" \
                  -backend-config="key=staging.terraform.tfstate"
                
                # Check if resource group is in Terraform state
                if ! terraform state list | grep -q azurerm_resource_group.rg; then
                  echo "Resource group not found in state. Importing..."
                  terraform import azurerm_resource_group.rg /subscriptions/$(SUBSCRIPTION_ID)/resourceGroups/$(resource_group_name_staging)
                else
                  echo "Resource group already managed by Terraform."
                fi

          - task: Bash@3
            displayName: 'Initialize and Apply Terraform (Staging)'
            inputs:
              workingDirectory: '$(tfWorkingDir)'
              targetType: 'inline'
              script: |
                export TF_LOG=DEBUG
                terraform apply -auto-approve -no-color \
                  -var="app_service_name=$(app_service_name_staging)" \
                  -var="resource_group_name=$(resource_group_name_staging)" \
                  -var="environment=$(environment_staging)"
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App (Staging)'
            inputs:
              azureSubscription: 'terraform-sc'
              appType: 'webAppLinux'
              appName: '$(app_service_name_staging)'
              package: '$(Pipeline.Workspace)/drop/app.zip'
              runtimeStack: 'PYTHON|3.10'
              startUpCommand: 'gunicorn --bind=0.0.0.0 --workers=4 app:app'

